---
- name: Set firefox_pkg based on distribution
  ansible.builtin.set_fact:
    firefox_pkg: "{{ 'firefox-esr' if ansible_distribution == 'Kali' else 'firefox' }}"
  tags: firefox

- name: Set firefox_profile_directory
  ansible.builtin.set_fact:
    firefox_mozilla_directory: "{{ vm_user_details.home }}{{ '/snap/firefox/common' if snap_check.rc == 0 }}/.mozilla"
    firefox_profile_directory: "{{ vm_user_details.home }}{{ '/snap/firefox/common' if snap_check.rc == 0 }}/.mozilla/firefox/ehacking.default"
  when: firefox_profile_directory is undefined
  tags: firefox

- name: Install Firefox Snap
  snap:
    name:
      - firefox
  tags: firefox
  when: snap_check.rc == 0

- name: Install Firefox via apt
  apt:
    pkg: "{{ firefox_pkg }}"
    state: latest
  tags: firefox
  when: snap_check.rc != 0

- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ vm_user }}"
    group: "{{ vm_user_details.group }}"
    mode: '0755'
  loop:
    - "{{ firefox_mozilla_directory }}/certificates"
    - "{{ firefox_profile_directory }}/bookmarkbackups/"
    - "{{ firefox_profile_directory }}/extensions/"
  tags: firefox

- name: Create Firefox Profile Directory
  ansible.builtin.file:
    path: "{{ firefox_profile_directory }}"
    state: directory
    mode: '0755'
    owner: "{{ vm_user }}"
    group: "{{ vm_user_details.group }}"
  tags: firefox

- name: Create Firefox profiles.ini
  ansible.builtin.template:
    src: profiles.ini.j2
    dest: "{{ firefox_mozilla_directory }}/firefox/profiles.ini"
    owner: "{{ vm_user }}"
    group: "{{ vm_user_details.group }}"
    mode: '0644'
  tags: firefox

- name: Copy bookmarks backup
  ansible.builtin.copy:
    src: bookmarks.json
    dest: "{{ firefox_profile_directory }}/bookmarkbackups/bookmarks.json"
    owner: "{{ vm_user }}"
    group: "{{ vm_user_details.group }}"
    mode: '0644'
  tags: firefox

- name: Write about:config-Prefs in user.js
  ansible.builtin.template:
    src: user.js.j2
    dest: "{{ firefox_profile_directory }}/user.js"
    owner: "{{ vm_user }}"
    group: "{{ vm_user_details.group }}"
    mode: '0644'
  tags: firefox

- name: Downoad FoxyProxy
  ansible.builtin.get_url:
    url: https://addons.mozilla.org/firefox/downloads/latest/foxyproxy-standard/addon-latest.xpi
    dest: "{{ role_path }}/files/foxyproxy.xpi"
    mode: '0644'
    owner: "{{ vm_user }}"
    group: "{{ vm_user_details.group }}"
    force: yes
  tags: firefox

- name: Install FoxyProxy-XPI
  ansible.builtin.copy:
    src: foxyproxy.xpi
    dest: "{{ firefox_profile_directory }}/extensions/foxyproxy@eric.h.jung.xpi"
    owner: "{{ vm_user }}"
    group: "{{ vm_user_details.group }}"
    mode: '0644'
  tags: firefox

- name: Activate Extensions
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ firefox_profile_directory }}/{{ item }}"
    owner: "{{ vm_user }}"
    group: "{{ vm_user_details.group }}"
    mode: '0644'
  loop:
    - "extensions.json"
    - "extension-preferences.json"
  tags: firefox

- name: Create the Firefox certificate database if it does not exist
  ansible.builtin.command: >
    bash -c "certutil -N -d sql:{{ firefox_profile_directory }} -f /dev/null"
  args:
    creates: "{{ firefox_profile_directory }}/cert9.db"
  tags: firefox

- name: Set possessor rights recursively.
  ansible.builtin.file:
    path: "{{ firefox_profile_directory }}"
    owner: "{{ vm_user }}"
    group: "{{ vm_user_details.group }}"
    recurse: yes
  tags: firefox