---
- name: Download 
  ansible.builtin.get_url:
    url: https://dl.pstmn.io/download/latest/linux64
    dest: /tmp/postman-linux-x64.tar.gz
    mode: '0644'
  tags: postman

- name: Extract
  ansible.builtin.unarchive:
    src: /tmp/postman-linux-x64.tar.gz
    dest: /opt
    remote_src: yes
    creates: /opt/Postman/app/Postman
  tags: postman

- name: Create symbolic link
  ansible.builtin.file:
    src: /opt/Postman/app/Postman
    dest: /usr/local/bin/Postman
    state: link
  tags: postman

# - name: Create Application Launcher
#   ansible.builtin.copy:
#     src: '{{ config_dir }}/applications/postman.desktop'
#     remote_src: yes
#     dest: "{{ item }}"
#     owner: "{{ vm_user }}"
#     group: "{{ vm_user_details.group }}"
#     mode: '0755'
#   loop:
#     - "{{ vm_user_details.home }}/Desktop/"
#     - "{{ vm_user_details.home }}/.local/share/applications/"
#   notify: trust desktop files
#   tags: postman