---
- hosts: all
  remote_user: vagrant
  become_user: root
  become: yes
  vars:
    config_system_locale: 'de_DE.UTF-8'
    config_system_timezone: 'Europe/Berlin'
    config_keyboard_layout: 'de'
    ehacking_docker: "2023-10-kali"
    config_dir: "{{ playbook_dir }}/../config/"
    vm_user: "student"
  roles:
    - ubuntu
    - common
    - firefox
    - chromium
    - apache
    - burpsuite
    - ehacking-docker
    - vscode